name: test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        while IFS='' read -r LINE || [ -n "${LINE}" ]; do
            diff <(python3 configure-argparse.py $LINE) <(python3 configure-optparse.py $LINE)
        done < args.txt
